# Default initial positions for rover_arm's ros2_control fake system

initial_positions:
  base_joint: 0
  elbow_pitch_joint: 1
  elbow_roll_joint: 0
  wrist_roll_joint: 0
  shoulder_joint: -1
  wrist_pitch_joint: 1.57